Repository prgrms-web-devcourse-final-project/WEB2_3_9crops_FE, pull requests merged in 2025-03, with the labels that each got.

#53 feat: 편지 게시글 공유 기능 구현 (mock api)
  src/apis/share.ts
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Home/components/GoToLetterBox.tsx
  src/pages/Home/components/HomeRight.tsx
  src/pages/Home/components/NewLetterModal.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/LetterBoardDetail/components/Letter.tsx
  src/pages/LetterBoardDetail/index.tsx
Labels: ✨ Feature

#66 feat: 읽지 않은 편지 수 조회 기능 구현
  src/apis/unreadLetters.ts
  src/pages/Home/components/HomeRight.tsx
  src/pages/Home/components/NewLetterModal.tsx
Labels: ✨ Feature

#67 feat : 편지작성, 랜덤편지 구현 90% 완료, 편지상세는 이후에 테스트
  src/apis/client.ts
  src/apis/letterDetail.ts
  src/apis/randomLetter.ts
  src/apis/write.ts
  src/components/ResultLetter.tsx
  src/layouts/Header.tsx
  src/pages/LetterDetail/index.tsx
  src/pages/RandomLetters/components/CoolTime.tsx
  src/pages/RandomLetters/components/Matched.tsx
  src/pages/RandomLetters/components/MatchedLetter.tsx
  src/pages/RandomLetters/components/MatchingSelect.tsx
  src/pages/RandomLetters/components/MatchingSelectModal.tsx
  src/pages/RandomLetters/index.tsx
  src/pages/Write/CategorySelect.tsx
  src/pages/Write/LetterEditor.tsx
  src/pages/Write/components/ResultLetterAnimation.tsx
  src/pages/Write/index.tsx
  src/stores/writeStore.ts
  src/types/random.d.ts
  src/types/write.d.ts
  src/utils/removeProperty.ts
  src/utils/timeFormatter.ts
Labels: ✨ Feature, 🔨 Refactor

#70 refactor: PR 리뷰를 반영한 리팩토링
  src/apis/unreadLetters.ts
  src/pages/Home/components/GoToLetterBox.tsx
  src/pages/Home/components/HomeRight.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/pages/Home/components/UnreadLetterModal.tsx
  src/types/unreadLetters.d.ts
Labels: 🔨 Refactor

#72 fix: 편지함 오류 수정
  src/apis/client.ts
  src/apis/mailBox.ts
  src/main.tsx
  src/pages/LetterBox/index.tsx
  src/pages/LetterBoxDetail/components/LetterPreview.tsx
  src/pages/LetterBoxDetail/index.tsx
  src/utils/formatDate.ts
Labels: 🐞 Bug

#75 feat: 임시저장된 편지 조회 기능 구현
  src/apis/draftLetters.ts
  src/apis/incomingLetters.ts
  src/pages/Home/components/ShowDraftModal.tsx
  src/stores/incomingLettersStore.ts
Labels: ✨ Feature

#84 feat: 임시저장된 편지 삭제 기능 구현
  src/apis/draftLetters.ts
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
Labels: ✨ Feature

#85 feat: 롤링페이퍼 배포된 api로 연결 수정
  eslint.config.js
  src/App.tsx
  src/apis/rolling.ts
  src/components/NoticeRollingPaper.tsx
  src/pages/Admin/RollingPaper.tsx
  src/pages/Admin/components/AddRollingPaperModal.tsx
  src/pages/Admin/components/RollingPaperItem.tsx
  src/pages/RollingPaper/components/CommentDetailModal.tsx
  src/pages/RollingPaper/index.tsx
  src/styles/animations.css
  src/styles/preflight.css
  src/types/rolling.d.ts
Labels: ✨ Feature

#81 feat : 알림 2차 기능 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/notification.ts
  src/hooks/useServerSentEvents.tsx
  src/pages/Notifications/components/NotificationItem.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Notifications/constants/index.ts
  src/pages/Notifications/index.tsx
  src/stores/sseStore.ts
  src/types/notifications.d.ts
Labels: ✨ Feature

#92 feat : 관리자 페이지 3차 기능구현
  src/pages/Admin/Report.tsx
  src/pages/Admin/components/PagenationNavigation.tsx
Labels: ✨ Feature

#90 feat: 편지 공유 요청 수신 조회 기능 구현
  src/apis/incomingLetters.ts
  src/apis/share.ts
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/stores/incomingLettersStore.ts
Labels: ✨ Feature

#95 feat: 롤링페이퍼 추가 기능 구현
  src/apis/rolling.ts
  src/components/BackgroundBottom.tsx
  src/components/ConfirmModal.tsx
  src/pages/Admin/RollingPaper.tsx
  src/pages/Admin/components/AddRollingPaperModal.tsx
  src/pages/Admin/components/PagenationNavigation.tsx
  src/pages/Admin/components/RollingPaperItem.tsx
  src/pages/LetterBoard/index.tsx
  src/pages/MyPage/components/MyBoardPage.tsx
  src/pages/RollingPaper/components/WriteCommentButton.tsx
  src/pages/RollingPaper/index.tsx
Labels: ✨ Feature

#97 feat: 임시저장 편지 조회 기능 완성
  src/apis/draftLetters.ts
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Home/components/ShowDraftModal.tsx
Labels: ✨ Feature

#98 feat : 토스트 UI 구현 + 알림 페이지 코드 작업 90% 완료 + 실시간 알림, 편지 작성 예외처리에 토스트UI 연결
  src/App.tsx
  src/apis/write.ts
  src/components/Toast.tsx
  src/components/ToastItem.tsx
  src/hooks/useServerSentEvents.tsx
  src/layouts/PrivateRoute.tsx
  src/pages/Notifications/components/SendingModal.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Notifications/constants/index.ts
  src/pages/Notifications/index.tsx
  src/pages/Write/LetterEditor.tsx
  src/stores/sseStore.ts
  src/stores/toastStore.ts
  src/styles/animations.css
  src/types/write.d.ts
Labels: ✨ Feature

#106 feat: 공유 요청 상세 조회 기능 구현
  src/App.tsx
  src/apis/share.ts
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/MyPage/constants/index.ts
  src/pages/Share/index.tsx
Labels: ✨ Feature

#109 fix: 임시저장 편지 작성 페이지 이동 경로 문제 해결
  src/pages/Home/components/ShowDraftModal.tsx
Labels: 🐞 Bug

#111 feat : 신고 등록 API + ReportModal 수정
  src/components/ReportModal.tsx
  src/types/admin.d.ts
Labels: ✨ Feature

#114 feat : 알림 기능 구현 + QA
  src/apis/admin.ts
  src/apis/notification.ts
  src/components/NotificationButton.tsx
  src/components/ReportModal.tsx
  src/components/ToastItem.tsx
  src/hooks/useServerSentEvents.tsx
  src/layouts/Header.tsx
  src/pages/Home/components/HomeHeader.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Notifications/index.tsx
  src/stores/notificationStore.ts
  src/types/notifications.d.ts
Labels: ✨ Feature, 🔨 Refactor

#115 feat : 편지 작성 QA 및 편지 임시저장 기능 구현 완료
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Write/CategorySelect.tsx
  src/pages/Write/LetterEditor.tsx
  src/pages/Write/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#116 refactor: 2차 QA 반영
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/MyPage/index.tsx
  src/pages/Share/index.tsx
  src/stores/incomingLettersStore.ts
  src/stores/myPageStore.ts
Labels: 🔨 Refactor

#122 feat : 2차 배포 수정
  src/hooks/useServerSentEvents.tsx
  src/pages/Admin/components/AddRollingPaperModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/Landing/constants/index.ts
  src/pages/LetterBoardDetail/index.tsx
  src/pages/RollingPaper/components/Comment.tsx
  src/pages/RollingPaper/components/CommentDetailModal.tsx
  src/pages/RollingPaper/components/WriteCommentButton.tsx
  src/pages/RollingPaper/index.tsx
Labels: 🌈 Deploy

#124 feat : 알림 QA 수정
  src/components/ToastItem.tsx
  src/hooks/useServerSentEvents.tsx
Labels: 🔨 Refactor

#126 deploy : 배포
  .github/workflows/deploy.yml
  src/main.tsx
  src/pages/Auth/index.tsx
  src/pages/LetterBoardDetail/index.tsx
Labels: 🌈 Deploy

#128 deploy : 배포 3트
  src/components/ToastItem.tsx
  src/hooks/useServerSentEvents.tsx
Labels: 🌈 Deploy

#131 fix: 3차 QA 반영
  .github/workflows/deploy.yml
  src/apis/share.ts
  src/components/MenuButton.tsx
  src/main.tsx
  src/pages/LetterBoardDetail/components/Header.tsx
  src/pages/LetterBoardDetail/components/Letter.tsx
  src/pages/LetterBoardDetail/index.tsx
  src/pages/LetterBoxDetail/index.tsx
  src/pages/RandomLetters/components/Matched.tsx
  src/pages/RandomLetters/components/MatchedLetter.tsx
  src/pages/RandomLetters/index.tsx
  src/pages/RollingPaper/index.tsx
Labels: 🐞 Bug

#141 feat : 금칙어 수정, 활성/비활성, 삭제 api 연결 완료
  src/apis/admin.ts
  src/pages/Admin/Filtering.tsx
  src/pages/Admin/components/AddInputButton.tsx
  src/pages/Admin/components/FilterTextItem.tsx
  src/pages/Admin/components/Sidebar.tsx
  src/types/admin.d.ts
Labels: ✨ Feature, 🔨 Refactor

#143 fix: 4차 QA 반영
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Share/index.tsx
Labels: 🐞 Bug

#146 deploy : 5차 배포
  .github/workflows/deploy.yml
  src/assets/images/background-dark.png
  src/assets/images/field-4-dark.png
  src/assets/images/field-theme-asset-bird-dark.png
  src/assets/images/home-left-mountain-dark.png
  src/assets/images/home-right-mountain-bottom-dark.png
  src/assets/images/home-right-mountain-top-dark.png
  src/assets/images/landing-dark.png
  src/layouts/PrivateRoute.tsx
  src/main.tsx
  src/pages/Auth/index.tsx
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/LetterBoardDetail/index.tsx
  src/pages/RollingPaper/index.tsx
Labels: 🌈 Deploy

#148 deploy : 5차 배포(수정본)
  src/layouts/PrivateRoute.tsx
  src/main.tsx
Labels: 🌈 Deploy

#152 fix : api reissue 오류 수정
  src/apis/client.ts
  src/hooks/useServerSentEvents.tsx
  src/layouts/PrivateRoute.tsx
  src/stores/authStore.ts
Labels: 🐞 Bug, 🔨 Refactor

#154 deploy : 6차 배포
  src/apis/client.ts
  src/hooks/useServerSentEvents.tsx
  src/layouts/PrivateRoute.tsx
  src/pages/RollingPaper/index.tsx
  src/stores/authStore.ts
Labels: 🌈 Deploy

#159 deploy : (수정)롤링페이퍼 버튼 1개 삭제
  src/pages/RollingPaper/index.tsx
Labels: 🌈 Deploy, 🔨 Refactor

#160 deploy : 6차 배포(수정)
  src/components/TextareaField.tsx
Labels: 🐞 Bug, 🌈 Deploy

#162 chore: README.md 업데이트
  README.md
Labels: 📃 Docs

#164 fix: aria-label 수정
  src/components/ConfirmModal.tsx
  src/components/MessageModal.tsx
  src/components/ReportModal.tsx
  src/pages/Admin/Filtering.tsx
  src/pages/Admin/RollingPaper.tsx
  src/pages/Admin/components/AddRollingPaperModal.tsx
  src/pages/Admin/components/FilterTextItem.tsx
  src/pages/Admin/components/MenuModal.tsx
  src/pages/Admin/components/PagenationNavigation.tsx
  src/pages/Admin/components/ReportHandlingModal.tsx
  src/pages/Admin/components/RollingPaperItem.tsx
  src/pages/Admin/components/Sidebar.tsx
  src/pages/Home/components/LetterActions.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/LetterBoardDetail/components/Header.tsx
  src/pages/LetterBoxDetail/index.tsx
  src/pages/LetterDetail/components/LetterDetailReplyButton.tsx
  src/pages/MyPage/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Notifications/components/SendingModal.tsx
  src/pages/Notifications/components/ShareModal.tsx
  src/pages/Notifications/index.tsx
  src/pages/Onboarding/SetZipCode.tsx
  src/pages/Onboarding/WelcomeLetter.tsx
  src/pages/RandomLetters/components/CoolTime.tsx
  src/pages/RandomLetters/components/Matched.tsx
  src/pages/RandomLetters/components/MatchedLetter.tsx
  src/pages/RandomLetters/components/MatchingSelect.tsx
  src/pages/RandomLetters/components/MatchingSelectModal.tsx
  src/pages/RollingPaper/components/CommentDetailModal.tsx
  src/pages/RollingPaper/components/WriteCommentButton.tsx
  src/pages/Share/index.tsx
  src/pages/Write/CategorySelect.tsx
Labels: 🐞 Bug

#167 refactor: 홈 페이지 성능 개선
  src/assets/images/background-overlay.png
  src/assets/images/background-overlay.webp
  src/assets/images/field-theme-asset-bird.png
  src/assets/images/field-theme-asset-bird.webp
  src/assets/images/go-to-letter-board.png
  src/assets/images/go-to-letter-board.webp
  src/assets/images/go-to-letter-box-new-letters.png
  src/assets/images/go-to-letter-box-new-letters.webp
  src/assets/images/go-to-letter-box.png
  src/assets/images/go-to-letter-box.webp
  src/assets/images/letter-1.png
  src/assets/images/letter-1.webp
  src/assets/images/letter-2.png
  src/assets/images/letter-2.webp
  src/assets/images/letter-3.png
  src/assets/images/letter-3.webp
  src/assets/images/letter-4.png
  src/assets/images/letter-4.webp
  src/assets/images/postoffice-letter.png
  src/assets/images/postoffice-letter.webp
  src/assets/images/postoffice.png
  src/assets/images/postoffice.webp
  src/pages/Home/components/FloatingLetters.tsx
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Home/components/GoToLetterBox.tsx
  src/pages/Home/components/GoToRandomLetter.tsx
  src/pages/Home/components/GoToWrite.tsx
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Login/components/Background.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Share/index.tsx
  src/styles/components.css
  src/styles/preflight.css
Labels: 🔨 Refactor

#169 perf: 홈 페이지 접근성 향상
  src/components/MenuButton.tsx
  src/pages/Home/components/HomeHeader.tsx
Labels: 🔨 Refactor

#171 refactor: 마이페이지 상태 관리 리팩토링
  src/apis/myPage.ts
  src/layouts/Header.tsx
  src/pages/MyPage/index.tsx
  src/stores/myPageStore.ts
  src/types/mypage.d.ts
Labels: 🔨 Refactor

#173 refactor: 타입 관리 리팩토링
  src/apis/draftLetters.ts
  src/apis/share.ts
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/LetterBoardDetail/index.tsx
  src/pages/Share/index.tsx
  src/types/draftLetters.d.ts
  src/types/share.d.ts
Labels: 🔨 Refactor
