Repository prgrms-web-devcourse-final-project/WEB2_3_9crops_FE, pull requests merged in 2025-02, with the labels that each got.

#2 design: 모바일 뷰 기본 틀 설정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/hooks/.gitkeep
  src/hooks/useViewport.ts
  src/styles/preflight.css
Labels: 🎨 Design

#8 design: 마이페이지 퍼블리싱
  src/App.tsx
  src/assets/icons/alarm.svg
  src/assets/icons/arrow-left.svg
  src/assets/icons/index.ts
  src/assets/icons/person.svg
  src/assets/images/background-overlay.png
  src/assets/images/yellow-modal.png
  src/components/.gitkeep
  src/components/ConfirmModal.tsx
  src/components/ModalOverlay.tsx
  src/hooks/useViewport.ts
  src/layouts/Header.tsx
  src/pages/MyPage/constants/index.ts
  src/pages/MyPage/index.tsx
  src/styles/components.css
  src/styles/preflight.css
  src/vite-env.d.ts
Labels: 🎨 Design

#10 design: 알림페이지 퍼블리싱
  src/App.tsx
  src/assets/icons/board.svg
  src/assets/icons/envelope.svg
  src/assets/icons/index.ts
  src/assets/icons/message.svg
  src/assets/icons/siren.svg
  src/components/ConfirmModal.tsx
  src/layouts/.gitkeep
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/pages/MyPage/index.tsx
  src/pages/Notifications/components/NotificationItem.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Notifications/constants/index.ts
  src/pages/Notifications/index.tsx
  src/styles/components.css
Labels: 🎨 Design

#14 design: 게시판 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/.gitkeep
  src/assets/icons/delete.svg
  src/assets/icons/index.ts
  src/assets/icons/like-filled.svg
  src/assets/icons/like-outlined.svg
  src/assets/icons/notice.svg
  src/assets/icons/siren-filled.svg
  src/assets/icons/siren-outlined.svg
  src/assets/images/field-4.png
  src/assets/images/memo-pink.png
  src/assets/images/memo-yellow.png
  src/assets/images/modal-pink.png
  src/assets/images/modal-yellow.png
  src/components/BackgroundBottom.tsx
  src/components/ConfirmModal.tsx
  src/components/MessageModal.tsx
  src/components/ModalOverlay.tsx
  src/components/NoticeRolling.tsx
  src/components/PageTitle.tsx
  src/components/ReportModal.tsx
  src/components/TextareaField.tsx
  src/layouts/Header.tsx
  src/pages/LetterBoard/components/LetterPreview.tsx
  src/pages/LetterBoard/index.tsx
  src/pages/LetterBoardDetail/components/Header.tsx
  src/pages/LetterBoardDetail/components/Letter.tsx
  src/pages/LetterBoardDetail/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/Notifications/components/WarningModal.tsx
  src/pages/Notifications/constants/index.ts
  src/pages/Notifications/index.tsx
  src/pages/RollingPaper/components/Message.tsx
  src/pages/RollingPaper/components/MessageDetailModal.tsx
  src/pages/RollingPaper/index.tsx
  src/styles/components.css
  src/styles/preflight.css
  src/styles/utilities.css
  src/utils/getScrollbarWidth.ts
Labels: 🎨 Design

#16 design: 내 편지함 페이지 퍼블리싱
  src/App.tsx
  src/assets/icons/index.ts
  src/assets/icons/infromation.svg
  src/assets/images/door.png
  src/components/BackgroundBottom.tsx
  src/components/BackgroundImageWrapper.tsx
  src/components/ConfirmModal.tsx
  src/components/ListItemWrapper.tsx
  src/components/MessageModal.tsx
  src/components/PageTitle.tsx
  src/components/TextareaField.tsx
  src/pages/LetterBoard/components/LetterPreview.tsx
  src/pages/LetterBoardDetail/components/Letter.tsx
  src/pages/LetterBox/components/LetterBoxItem.tsx
  src/pages/LetterBox/index.tsx
  src/pages/LetterBoxDetail/components/InformationTooltip.tsx
  src/pages/LetterBoxDetail/components/LetterPreview.tsx
  src/pages/LetterBoxDetail/index.tsx
  src/pages/Notifications/components/NotificationItem.tsx
  src/pages/Notifications/index.tsx
  src/pages/RollingPaper/components/Message.tsx
  src/pages/RollingPaper/components/MessageDetailModal.tsx
  src/styles/components.css
  src/styles/preflight.css
  src/utils/.gitkeep
  src/utils/chunkBox.ts
Labels: 🎨 Design

#17 design : 랜덤 편지 페이지 & 편지 상세 페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/assets/icons/cloud.svg
  src/assets/icons/color-siren.svg
  src/assets/icons/index.ts
  src/assets/icons/restart.svg
  src/assets/icons/snow.svg
  src/assets/icons/thermostat.svg
  src/assets/icons/warm.svg
  src/assets/images/field-4.png
  src/pages/LetterDetail/index.tsx
  src/pages/RandomLetters/Matched.tsx
  src/pages/RandomLetters/MatchingSelect.tsx
  src/pages/RandomLetters/MatchingSelectModal.tsx
  src/pages/RandomLetters/index.tsx
  src/pages/Write/CategorySelect.tsx
  src/pages/Write/LetterEditor.tsx
  src/pages/Write/OptionSlide.tsx
  src/pages/Write/components/FontOption.tsx
  src/pages/Write/components/PreviousLetterOption.tsx
  src/pages/Write/components/ResultLetterAnimation.tsx
  src/pages/Write/components/ThemeOption.tsx
  src/pages/Write/components/WritePageButton.tsx
  src/pages/Write/index.tsx
  src/styles/animations.css
  src/types/random.d.ts
Labels: 🎨 Design

#19 design: 홈 페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/assets/images/go-to-letter-board.png
  src/assets/images/go-to-letter-box-new-letters.png
  src/assets/images/go-to-letter-box.png
  src/assets/images/go-to-random-letter.png
  src/assets/images/go-to-write.png
  src/assets/images/home-left-mountain.png
  src/assets/images/home-right-mountain-bottom.png
  src/assets/images/home-right-mountain-top.png
  src/assets/images/letter-1.png
  src/assets/images/letter-2.png
  src/assets/images/letter-3.png
  src/assets/images/letter-4.png
  src/assets/images/random-cheer-bird.png
  src/components/HomeButton.tsx
  src/pages/Home/components/FloatingLetters.tsx
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Home/components/GoToLetterBox.tsx
  src/pages/Home/components/GoToRandomLetter.tsx
  src/pages/Home/components/GoToWrite.tsx
  src/pages/Home/components/HomeBackgroundLeft.tsx
  src/pages/Home/components/HomeBackgroundRightBottom.tsx
  src/pages/Home/components/HomeBackgroundRightTop.tsx
  src/pages/Home/components/HomeHeader.tsx
  src/pages/Home/components/HomeLeft.tsx
  src/pages/Home/components/HomeRight.tsx
  src/pages/Home/components/LetterActions.tsx
  src/pages/Home/components/LetterPreview.tsx
  src/pages/Home/components/NewLetterModal.tsx
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/Home/components/SpecialLetterBanner.tsx
  src/pages/Home/constants/index.ts
  src/pages/Home/index.tsx
  src/styles/animations.css
Labels: 🎨 Design

#22 design: 로그인 및 랜딩 페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/icons/google.svg
  src/assets/icons/index.ts
  src/assets/icons/information.svg
  src/assets/icons/kakao.svg
  src/assets/icons/naver.svg
  src/assets/icons/stamp.svg
  src/assets/images/go-to-write.png
  src/assets/images/landing-blur.png
  src/assets/images/landing.png
  src/assets/images/postoffice-letter.png
  src/assets/images/postoffice.png
  src/pages/Home/components/GoToWrite.tsx
  src/pages/Landing/constants/index.ts
  src/pages/Landing/index.tsx
  src/pages/LetterDetail/index.tsx
  src/pages/Login/components/Background.tsx
  src/pages/Login/index.tsx
  src/styles/animations.css
  src/styles/fonts.css
  src/styles/preflight.css
  src/styles/theme.css
Labels: 🎨 Design

#25 design: 홈 페이지 공유 미리보기 퍼블리싱
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/LetterBoardDetail/components/Header.tsx
  src/pages/LetterBoardDetail/index.tsx
Labels: 🎨 Design

#28 design, feat, chore : 편지 작성 페이지 추가 퍼블리싱 + 기능구현 + API연결 + 관리자페이지 퍼블리싱
  src/App.tsx
  src/apis/letterDetail.ts
  src/apis/write.ts
  src/assets/icons/arrow-down.svg
  src/assets/icons/check.svg
  src/assets/icons/index.ts
  src/assets/icons/kebob-menu.svg
  src/components/BackButton.tsx
  src/components/ResultLetter.tsx
  src/layouts/MobileLayout.tsx
  src/pages/Admin/Report.tsx
  src/pages/Admin/admin.d.ts
  src/pages/Admin/components/DetailFrame.tsx
  src/pages/Admin/components/ListItem.tsx
  src/pages/Admin/components/MenuModal.tsx
  src/pages/Admin/components/WrapperFrame.tsx
  src/pages/Admin/index.tsx
  src/pages/LetterDetail/index.tsx
  src/pages/RandomLetters/Matched.tsx
  src/pages/RandomLetters/MatchingSelect.tsx
  src/pages/RandomLetters/MatchingSelectModal.tsx
  src/pages/RandomLetters/index.tsx
  src/pages/Write/CategorySelect.tsx
  src/pages/Write/LetterEditor.tsx
  src/pages/Write/OptionSlide.tsx
  src/pages/Write/components/CategoryList.tsx
  src/pages/Write/components/CategoryStamp.tsx
  src/pages/Write/components/CheckIcon.tsx
  src/pages/Write/components/FontOption.tsx
  src/pages/Write/components/PreviousLetterOption.tsx
  src/pages/Write/components/ResultLetterAnimation.tsx
  src/pages/Write/components/ThemeOption.tsx
  src/pages/Write/components/WritePageButton.tsx
  src/pages/Write/constants/index.ts
  src/pages/Write/index.tsx
  src/stores/writeStore.ts
  src/styles/components.css
  src/styles/preflight.css
  src/styles/typography.css
  src/types/letterDetail.d.ts
  src/types/random.d.ts
  src/types/write.d.ts
Labels: 🎨 Design, ✨ Feature, 🔨 Refactor

#33 design: 404 페이지 퍼블리싱
  src/App.tsx
  src/pages/NotFound/index.tsx
Labels: 🎨 Design

#35 feat: 롤링페이퍼 기능 구현 (mock api)
  src/apis/rolling.ts
  src/assets/images/letter-pink.png
  src/assets/images/memo-pink.png
  src/assets/images/memo-yellow.png
  src/assets/images/modal-pink.png
  src/assets/images/modal-yellow.png
  src/assets/images/random-cheer-bird.png
  src/components/ConfirmModal.tsx
  src/components/LetterWrapper.tsx
  src/components/MemoWrapper.tsx
  src/components/MessageModal.tsx
  src/components/ModalBackgroundWrapper.tsx
  src/components/NoticeRolling.tsx
  src/components/NoticeRollingPaper.tsx
  src/components/ResultLetter.tsx
  src/components/TextareaField.tsx
  src/main.tsx
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Home/components/ShowDraftModal.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/pages/Home/components/ShowShareAccessModal.tsx
  src/pages/Home/components/SpecialLetterBanner.tsx
  src/pages/Home/index.tsx
  src/pages/LetterBoard/components/LetterPreview.tsx
  src/pages/LetterBoard/index.tsx
  src/pages/LetterBoardDetail/components/Letter.tsx
  src/pages/LetterBoxDetail/components/LetterPreview.tsx
  src/pages/Notifications/components/NotificationItem.tsx
  src/pages/RollingPaper/components/Comment.tsx
  src/pages/RollingPaper/components/CommentDetailModal.tsx
  src/pages/RollingPaper/components/Message.tsx
  src/pages/RollingPaper/components/MessageDetailModal.tsx
  src/pages/RollingPaper/components/WriteCommentButton.tsx
  src/pages/RollingPaper/index.tsx
  src/styles/animations.css
  src/styles/components.css
  src/types/.gitkeep
  src/types/rolling.d.ts
Labels: ✨ Feature

#36 feat: 오고 있는 편지 조회 기능 구현 (mock api)
  src/apis/incomingLetters.ts
  src/pages/Home/components/FloatingLetters.tsx
  src/pages/Home/components/GoToLetterBoard.tsx
  src/pages/Home/components/GoToLetterBox.tsx
  src/pages/Home/components/GoToRandomLetter.tsx
  src/pages/Home/components/HomeBackgroundLeft.tsx
  src/pages/Home/components/HomeBackgroundRightBottom.tsx
  src/pages/Home/components/HomeBackgroundRightTop.tsx
  src/pages/Home/components/HomeLeft.tsx
  src/pages/Home/components/HomeRight.tsx
  src/pages/Home/components/LetterActions.tsx
  src/pages/Home/components/LetterPreview.tsx
  src/pages/Home/components/NewLetterModal.tsx
  src/pages/Home/components/RandomCheer.tsx
  src/pages/Home/components/ShowIncomingLettersModal.tsx
  src/stores/incomingLettersStore.ts
Labels: ✨ Feature

#39 feat: 마이페이지 내 정보 조회 기능 구현 (mock api)
  src/apis/incomingLetters.ts
  src/apis/myPage.ts
  src/pages/MyPage/index.tsx
  src/stores/myPageStore.ts
Labels: ✨ Feature

#43 feat:관리자 페이지 1차 기능 구현
  src/App.tsx
  src/apis/admin.ts
  src/assets/icons/add.svg
  src/assets/icons/cancel.svg
  src/assets/icons/index.ts
  src/pages/Admin/FilteredLetter.tsx
  src/pages/Admin/Filtering.tsx
  src/pages/Admin/Report.tsx
  src/pages/Admin/admin.d.ts
  src/pages/Admin/components/AddInputButton.tsx
  src/pages/Admin/components/DetailFrame.tsx
  src/pages/Admin/components/FilteredLetterListItem.tsx
  src/pages/Admin/components/ListHeaderFrame.tsx
  src/pages/Admin/components/ListItem.tsx
  src/pages/Admin/components/MenuModal.tsx
  src/pages/Admin/components/ReportDetailModal.tsx
  src/pages/Admin/components/ReportHandlingModal.tsx
  src/pages/Admin/components/ReportListItem.tsx
  src/pages/Admin/components/WrapperFrame.tsx
  src/pages/Admin/components/WrapperTitle.tsx
  src/pages/Admin/constants/index.ts
  src/pages/Admin/index.tsx
  src/styles/components.css
  src/types/admin.d.ts
Labels: 🎨 Design, ✨ Feature

#47 feat:편지 작성 페이지 1차 기능구현
  src/apis/letterDetail.ts
  src/apis/write.ts
  src/components/ResultLetter.tsx
  src/pages/Write/CategorySelect.tsx
  src/pages/Write/LetterEditor.tsx
  src/pages/Write/OptionSlide.tsx
  src/pages/Write/components/CategoryStamp.tsx
  src/pages/Write/components/FontOption.tsx
  src/pages/Write/components/ResultLetterAnimation.tsx
  src/pages/Write/components/ThemeOption.tsx
  src/pages/Write/components/WritePageButton.tsx
  src/pages/Write/index.tsx
  src/stores/writeStore.ts
  src/types/write.d.ts
Labels: ✨ Feature

#46 feat:랜덤 편지 + 편지 상세 1차 기능 구현
  src/apis/letterDetail.ts
  src/apis/randomLetter.ts
  src/components/ResultLetter.tsx
  src/pages/LetterDetail/index.tsx
  src/pages/RandomLetters/Matched.tsx
  src/pages/RandomLetters/MatchingSelect.tsx
  src/pages/RandomLetters/components/CoolTime.tsx
  src/pages/RandomLetters/components/Matched.tsx
  src/pages/RandomLetters/components/MatchedLetter.tsx
  src/pages/RandomLetters/components/MatchingSelect.tsx
  src/pages/RandomLetters/components/MatchingSelectModal.tsx
  src/pages/RandomLetters/constants/index.ts
  src/pages/RandomLetters/index.tsx
  src/types/letterDetail.d.ts
  src/types/random.d.ts
  src/utils/formatNumber.ts
Labels: ✨ Feature
